// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sopotgzzuriuxkisueqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvcG90Z3p6dXJpdXhraXN1ZXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjE5MjMsImV4cCI6MjA3MDA5NzkyM30.Ibsv8FVyzJCxM6ISqvGjTSt29CwB9DWnxBTLfY6ENZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});